apiVersion: certs.k8c.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: certificate-issuer
    app.kubernetes.io/managed-by: kustomize
  name: certificate-sample
spec:
  # TODO(user): Add fields here
